volumes:
  beca_n8n_data:
  beca_n8n_postgres_data:
  beca_postgres_data:
  beca_qdrant_data:
  beca_ollama_data:


networks:
  beca_network:


x-n8n: &service-n8n
  image: n8nio/n8n:1.122.5
  networks: [ 'beca_network' ]
  environment:
    - DB_TYPE=postgresdb
    - DB_POSTGRESDB_HOST=db
    - DB_POSTGRESDB_USER=${POSTGRES_USER}
    - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD}
    - N8N_DIAGNOSTICS_ENABLED=false
    - N8N_PERSONALIZATION_ENABLED=false
    - N8N_ENCRYPTION_KEY
    - N8N_USER_MANAGEMENT_JWT_SECRET
    - OLLAMA_HOST=${OLLAMA_HOST:-beca_ollama:11434}
  env_file:
    - path: .env
      required: true
  user: "node"
  working_dir: /home/node/.n8n
  depends_on:
    n8n_db:
      condition: service_healthy
  healthcheck:
    test: [ 'CMD', 'curl', '-f', 'http://localhost:5678/rest/healthz' ]
    interval: 30s
    timeout: 5s
    retries: 3
  # extra_hosts:
  #   - "host.docker.internal:host-gateway"

x-ollama: &service-ollama
  image: ollama/ollama:0.13.1
  networks: [ 'beca_network' ]
  hostname: ollama
  restart: unless-stopped
  ports:
    - 11434:11434
  volumes:
    - ./instance/ollama_data/ollama:/root/.ollama
    - ./instance/ollama_data/models:/root/.ollama/models

x-init-ollama: &init-ollama
  <<: *service-ollama
  entrypoint: /bin/sh
  environment:
    - OLLAMA_HOST=${OLLAMA_HOST:-beca_ollama:11434}
    - OLLAMA_MODEL=${OLLAMA_MODEL:-llama3.2:latest}
  command:
    - "-c"
    - "sleep 3; ollama pull ${OLLAMA_MODEL:-llama3.2:latest}"
  env_file:
    - path: .env
      required: true
  ports:
    - 11435:11434

x-postgres: &service-postgres
  image: postgres:18-alpine
  networks: [ 'beca_network' ]
  restart: unless-stopped
  healthcheck:
    test: [ 'CMD-SHELL', 'pg_isready -h localhost -U ${POSTGRES_USER} -d ${POSTGRES_DB}' ]
    interval: 5s
    timeout: 5s
    retries: 10
  env_file:
    - path: .env.db
      required: true

x-postgres-n8n: &service-postgres-n8n
  <<: *service-postgres
  env_file:
    - path: .env
      required: true

x-postgres-import: &service-postgres-import
  <<: *service-postgres
  entrypoint: /bin/sh
  restart: no
  volumes:
    - ./instance/database:/backup
  depends_on:
    postgres:
      condition: service_healthy

x-postgres-import-n8n: &service-postgres-import-n8n
  <<: *service-postgres-import
  env_file:
    - path: .env
      required: true
  depends_on:
    n8n_db:
      condition: service_healthy

x-postgres-upgrade: &service-postgres-upgrade
  image: pgautoupgrade/pgautoupgrade
  restart: no
  env_file:
    - path: .env.db
      required: true

services:

  n8n_server:
    <<: *service-n8n
    profiles: [ "cpu", "gpu-nvidia", "gpu-amd" ]
    hostname: n8n
    container_name: beca_n8n_server
    restart: unless-stopped
    ports:
      - 5678:5678
    volumes:
      - ./instance/n8n_data:/home/node/.n8n
      - ./include/custom/dist:/home/node/.n8n/custom
      - ./include/uploads:/home/node/uploads

  qdrant:
    image: qdrant/qdrant
    profiles: [ "cpu", "gpu-nvidia", "gpu-amd" ]
    hostname: qdrant
    networks: [ 'beca_network' ]
    restart: unless-stopped
    ports:
      - 6333:6333
    volumes:
      - ./instance/qdrant_data:/qdrant/storage

  postgres:
    <<: *service-postgres
    profiles: [ "cpu", "gpu-nvidia", "gpu-amd", "export", "import" ]
    hostname: postgres
    volumes:
      - ./instance/postgres_data:${POSTGRES_DATA_PATH:-/var/lib/postgresql}
      - ./include/init.sql:/docker-entrypoint-initdb.d/init.sql

  n8n_db:
    <<: *service-postgres-n8n
    profiles: [ "cpu", "gpu-nvidia", "gpu-amd", "export", "import" ]
    hostname: db
    volumes:
      - ./instance/n8n_postgres_data:${POSTGRES_DATA_PATH:-/var/lib/postgresql}

  n8n_import:
    <<: *service-n8n
    profiles: [ "import" ]
    entrypoint: /bin/sh
    command:
      - "-c"
      - "n8n import:credentials --separate --input=/home/node/uploads/credentials; n8n import:workflow --separate --input=/home/node/uploads/workflows; cp -u /home/node/uploads/credentials/config /home/node/.n8n/config"
    volumes:
      - ./include/uploads:/home/node/uploads
      - ./instance/credentials:/home/node/uploads/credentials

  n8n_export:
    <<: *service-n8n
    profiles: [ "export" ]
    entrypoint: /bin/sh
    command:
      - "-c"
      - "n8n export:credentials --backup --output=/home/node/uploads/credentials; n8n export:workflow --backup --output=/home/node/uploads/workflows; cp -u /home/node/.n8n/config /home/node/uploads/credentials/config"
    volumes:
      - ./include/uploads:/home/node/uploads
      - ./instance/credentials:/home/node/uploads/credentials

  postgres_import:
    <<: *service-postgres-import
    profiles: [ "import" ]
    command:
      - "-c"
      - "psql -h postgres -U ${POSTGRES_USER} -d ${POSTGRES_DB} < /backup/postgres.sql"

  n8n_postgres_import:
    <<: *service-postgres-import-n8n
    profiles: [ "import" ]
    command:
      - "-c"
      - "psql -h db -U ${POSTGRES_USER} -d ${POSTGRES_DB} < /backup/n8n.sql"

  postgres_export:
    <<: *service-postgres-import
    profiles: [ "export" ]
    command:
      - "-c"
      - "pg_dump -h postgres -U ${POSTGRES_USER} -d ${POSTGRES_DB} > /backup/postgres.$(date +%s).sql && pg_dump -h postgres -U ${POSTGRES_USER} -d ${POSTGRES_DB} > /backup/postgres.sql"

  n8n_postgres_export:
    <<: *service-postgres-import-n8n
    profiles: [ "export" ]
    command:
      - "-c"
      - "pg_dump -h db -U ${POSTGRES_USER} -d ${POSTGRES_DB} > /backup/n8n.$(date +%s).sql && pg_dump -h db -U ${POSTGRES_USER} -d ${POSTGRES_DB} > /backup/n8n.sql"

  postgres_upgrade:
    <<: *service-postgres-upgrade
    profiles: [ "migration" ]
    volumes:
      - ./instance/postgres_data:/var/lib/postgresql

  n8n_postgres_upgrade:
    <<: *service-postgres-upgrade
    profiles: [ "migration" ]
    volumes:
      - ./instance/n8n_postgres_data:/var/lib/postgresql
    env_file:
      - path: .env
        required: true

  ollama-cpu:
    profiles: [ "cpu" ]
    <<: *service-ollama

  ollama-gpu:
    profiles: [ "gpu-nvidia" ]
    <<: *service-ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]

  ollama-gpu-amd:
    profiles: [ "gpu-amd" ]
    <<: *service-ollama
    image: ollama/ollama:0.13.1-rocm
    devices:
      - "/dev/kfd"
      - "/dev/dri"

  ollama-pull-llama-cpu:
    profiles: [ "cpu" ]
    <<: *init-ollama
    depends_on:
      - ollama-cpu

  ollama-pull-llama-gpu:
    profiles: [ "gpu-nvidia" ]
    <<: *init-ollama
    depends_on:
      - ollama-gpu

  ollama-pull-llama-gpu-amd:
    profiles: [ "gpu-amd" ]
    <<: *init-ollama
    image: ollama/ollama:rocm
    depends_on:
      - ollama-gpu-amd
