volumes:
  beca_n8n_data:
  beca_n8n_postgres_data:
  beca_postgres_data:
  beca_qdrant_data:
  beca_ollama_data:


networks:
  beca_network:


x-n8n: &service-n8n
  image: n8nio/n8n:1.120.2
  networks: [ 'beca_network' ]
  environment:
    - DB_TYPE=postgresdb
    - DB_POSTGRESDB_HOST=db
    - DB_POSTGRESDB_USER=${POSTGRES_USER}
    - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD}
    - N8N_DIAGNOSTICS_ENABLED=false
    - N8N_PERSONALIZATION_ENABLED=false
    - N8N_ENCRYPTION_KEY
    - N8N_USER_MANAGEMENT_JWT_SECRET
    - OLLAMA_HOST=${OLLAMA_HOST:-beca_ollama:11434}
  env_file:
    - path: .env
      required: true
  user: "node"

x-ollama: &service-ollama
  image: ollama/ollama:0.12.11
  container_name: beca_ollama
  networks: [ 'beca_network' ]
  restart: unless-stopped
  ports:
    - 11434:11434
  volumes:
    - ./instance/ollama_data/ollama:/root/.ollama
    - ./instance/ollama_data/models:/root/.ollama/models

x-init-ollama: &init-ollama
  image: ollama/ollama:0.12.11
  networks: [ 'beca_network' ]
  container_name: beca_ollama_pull
  volumes:
    - ./instance/ollama_data/ollama:/root/.ollama
  entrypoint: /bin/sh
  environment:
    - OLLAMA_HOST=${OLLAMA_HOST:-beca_ollama:11434}
    - OLLAMA_MODEL=${OLLAMA_MODEL:-llama3.2:latest}
  command:
    - "-c"
    - "sleep 3; ollama pull ${OLLAMA_MODEL}"
  env_file:
    - path: .env
      required: true

services:

  postgres:
    image: postgres:16-alpine
    hostname: postgres
    container_name: beca_postgres
    networks: [ 'beca_network' ]
    restart: unless-stopped
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    env_file:
      - path: .env.db
        required: true
    volumes:
      - ./instance/postgres_data:/var/lib/postgresql/data
      - ./include/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -h localhost -U ${POSTGRES_USER} -d ${POSTGRES_DB}' ]
      interval: 5s
      timeout: 5s
      retries: 10

  n8n_db:
    image: postgres:15-alpine
    hostname: db
    container_name: beca_n8n_db
    networks: [ 'beca_network' ]
    restart: unless-stopped
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - ./instance/n8n_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -h localhost -U ${POSTGRES_USER} -d ${POSTGRES_DB}' ]
      interval: 5s
      timeout: 5s
      retries: 10

  n8n_import:
    <<: *service-n8n
    hostname: n8n_import
    container_name: beca_n8n_import
    entrypoint: /bin/sh
    command:
      - "-c"
      - "n8n import:credentials --separate --input=/home/node/uploads/credentials; n8n import:workflow --separate --input=/home/node/uploads/workflows; cp -u /home/node/uploads/credentials/config /home/node/.n8n/config"
    volumes:
      - ./include/uploads:/home/node/uploads
      - ./instance/credentials:/home/node/uploads/credentials
    depends_on:
      n8n_db:
        condition: service_healthy

  n8n_export:
    <<: *service-n8n
    profiles: [ "backup" ]
    hostname: n8n_export
    container_name: beca_n8n_export
    entrypoint: /bin/sh
    command:
      - "-c"
      - "n8n export:credentials --backup --output=/home/node/uploads/credentials; n8n export:workflow --backup --output=/home/node/uploads/workflows; cp -u /home/node/.n8n/config /home/node/uploads/credentials/config"
    volumes:
      - ./include/uploads:/home/node/uploads
      - ./instance/credentials:/home/node/uploads/credentials
    depends_on:
      n8n_db:
        condition: service_healthy

  n8n_server:
    <<: *service-n8n
    hostname: n8n
    container_name: beca_n8n
    restart: unless-stopped
    working_dir: /home/node/.n8n
    ports:
      - 5678:5678
    volumes:
      - ./instance/n8n_data:/home/node/.n8n
      - ./include/custom/dist:/home/node/.n8n/custom
      - ./include/uploads:/home/node/uploads
    depends_on:
      n8n_db:
        condition: service_healthy
      n8n_import:
        condition: service_completed_successfully
    healthcheck:
      test: [ 'CMD', 'curl', '-f', 'http://localhost:5678/rest/healthz' ]
      interval: 30s
      timeout: 5s
      retries: 3
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"

  qdrant:
    image: qdrant/qdrant
    hostname: qdrant
    container_name: beca_qdrant
    networks: [ 'beca_network' ]
    restart: unless-stopped
    ports:
      - 6333:6333
    volumes:
      - ./instance/qdrant_data:/qdrant/storage

  ollama-cpu:
    profiles: [ "cpu" ]
    <<: *service-ollama

  ollama-gpu:
    profiles: [ "gpu-nvidia" ]
    <<: *service-ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]

  ollama-gpu-amd:
    profiles: [ "gpu-amd" ]
    <<: *service-ollama
    image: ollama/ollama:rocm
    devices:
      - "/dev/kfd"
      - "/dev/dri"

  ollama-pull-llama-cpu:
    profiles: [ "cpu" ]
    <<: *init-ollama
    depends_on:
      - ollama-cpu

  ollama-pull-llama-gpu:
    profiles: [ "gpu-nvidia" ]
    <<: *init-ollama
    depends_on:
      - ollama-gpu

  ollama-pull-llama-gpu-amd:
    profiles: [ gpu-amd ]
    <<: *init-ollama
    image: ollama/ollama:rocm
    depends_on:
      - ollama-gpu-amd
